# Generated by Django 5.2 on 2025-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='thumbnail',
            field=models.ImageField(default='no image', upload_to='images'),
        ),
    ]
