# Generated by Django 5.1.4 on 2025-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movies_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='thumbnail',
            field=models.ImageField(default='images', upload_to='images'),
        ),
    ]
