# Generated by Django 5.2 on 2025-05-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movies_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
                ('certified_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='censor_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='movie_app.censordetail'),
        ),
    ]
